version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - VITE_AIR_QUALITY_OPEN_DATA_PLATFORM_API_KEY=$VITE_AIR_QUALITY_OPEN_DATA_PLATFORM_API_KEY
        - VITE_MERRIAM_WEBMASTER_DICT_API_KEY=$VITE_MERRIAM_WEBMASTER_DICT_API_KEY
    ports:
      - "8083:80"
    env_file:
      - .env